### ISSUE TITLE
Configuration does not work

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-multi-client-check#10]
Upgrade to the latest version (https://github.com/azerothcore/mod-multi-client-check/commit/47e25b870bf6ed6794de3828d73051fcf7095fa4), configuration does not work

Only two clients are allowed on the same network
![image](https://user-images.githubusercontent.com/18187177/111287518-436ab500-867e-11eb-8746-7cbaa8e97061.png)

But you can login to three clients
![image](https://user-images.githubusercontent.com/18187177/111288079-d277cd00-867e-11eb-8ae7-b115ebac0b8d.png)

This commit works:
https://github.com/azerothcore/mod-multi-client-check/commit/66a2f060fb66de2c1c3c3348f22bdaf5b80afdd8

**Comment by mpfans** [comment]
@UltraNix Please help me, I will add the bounty

**Comment by UltraNix** [comment]
@mpfans Problem here is that `configMgr` do not read values from this specific module conf file.

**Comment by ghost** [comment]
@mpfans It works okay to me. Remember to rename the config name in the main config folder (bin/Release/configs/modules/mod_multilogin.conf.dist) to mod_multilogin.conf

**Comment by mpfans** [comment]
> @mpfans It works okay to me. Remember to rename the config name in the main config folder (bin/Release/configs/modules/mod_multilogin.conf.dist) to mod_multilogin.conf

yes. 
![image](https://user-images.githubusercontent.com/18187177/116213432-6063cf00-a778-11eb-9f6b-f1741785cb8e.png)

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/116213849-b5074a00-a778-11eb-84bc-34f51f2cfe50.png)

**Comment by ghost** [comment]
And in that .conf file you have changed that variables?

**Comment by mpfans** [comment]
> And in that .conf file you have changed that variables?

![image](https://user-images.githubusercontent.com/18187177/116214143-00215d00-a779-11eb-948f-c660f73a5493.png)

**Comment by ghost** [comment]
Hmm, weird.
I set that to 1 and when I'm trying login with the second char, it gets disconnected immediately.

**Comment by mpfans** [comment]
> Hmm, weird.
> I set that to 1 and when I'm trying login with the second char, it gets disconnected immediately.

https://github.com/azerothcore/mod-multi-client-check/commit/66a2f060fb66de2c1c3c3348f22bdaf5b80afdd8

This commit works normally, but it doesn't work when it is updated later

**Comment by mpfans** [comment]
set to 1

![image](https://user-images.githubusercontent.com/18187177/116217904-986d1100-a77c-11eb-95f4-8017075e235a.png)

**Comment by ghost** [comment]
So I can't help you as it works okay on my local server.

**Comment by mpfans** [comment]
> So I can't help you as it works okay on my local server.

Try using mod-antichat and mod-multi-client check modules at the same time

**Comment by mpfans** [comment]
I have no custom code and only use these two modules

**Comment by ghost** [comment]
```
void OnLogin(Player* player)
    {
        uint32 CountLimit = sConfigMgr->GetIntDefault("Disallow.Multiple.Client", 0);
	if (CountLimit>0)
```
Try to debug that line if it returns value > 0.

**Comment by mpfans** [comment]
> ```
> void OnLogin(Player* player)
>     {
>         uint32 CountLimit = sConfigMgr->GetIntDefault("Disallow.Multiple.Client", 0);
> 	if (CountLimit>0)
> ```
> 
> Try to debug that line if it returns value > 0.

Please accept my application at discord

**Comment by mpfans** [comment]
updated to https://github.com/azerothcore/azerothcore-wotlk/commit/681c3237dfaf46bcad02f00ce717b97bdd899f40

configuration work!

I don't know which commit fixed the bug
