### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-multi-client-check#8]
update to https://github.com/azerothcore/azerothcore-wotlk/commit/dbefa17a534500522a174e9906d8923445c16e79

Compilation error
 error log:
`[ 98%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-anticheat-master/src/AnticheatScripts.cpp.o`
`/home/azerothcore/azerothcore/modules/mod-multi-client-check/src/mod_multilogincheck.cpp:69:16: fatal error: no member named 'LoadMore' in 'ConfigMgr'`
                        `sConfigMgr->LoadMore(cfg_def_file.c_str());`

ubuntu 18.04
AC commit :dbefa17a534500522a174e9906d8923445c16e79

**Comment by Helias** [comment]
should be solved here https://github.com/azerothcore/mod-multi-client-check/pull/9
